apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  labels:
    app: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: erfanrider/tickets
          env:
            - name: MONGO_URL
              value: "mongodb://tickets-mongo-srv-cluster:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv-cluster
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
